# Generated by Django 3.0.2 on 2020-02-02 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre', max_length=100)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('toDoFor', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='(no task)', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostitTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('postit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostIt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
        ),
        migrations.AddField(
            model_name='postit',
            name='tasks',
            field=models.ManyToManyField(to='app.Task'),
        ),
        migrations.AddField(
            model_name='postit',
            name='user',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
