# Generated by Django 3.0 on 2019-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password1',
            field=models.CharField(default='rqpVnbxzUM', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='password2',
            field=models.CharField(default='rqpVnbxzUM', max_length=200),
        ),
    ]
