# Generated by Django 3.0 on 2019-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191215_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
        migrations.AlterField(
            model_name='person',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
