# Generated by Django 3.0 on 2019-12-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191216_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password1',
        ),
    ]
