# Generated by Django 3.0 on 2019-12-19 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_person_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre', max_length=100)),
                ('content', models.TextField(default='Contenu')),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('toDoFor', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
