# Generated by Django 3.0 on 2019-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_postit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='(no task)', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postit',
            name='content',
            field=models.CharField(default='Contenu', max_length=500),
        ),
    ]
