# Generated by Django 3.0 on 2019-12-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191230_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostIt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
        ),
        migrations.AddField(
            model_name='postit',
            name='tasks',
            field=models.ManyToManyField(related_name='postits', through='app.PostItTask', to='app.Task'),
        ),
    ]
