# Generated by Django 3.0 on 2020-01-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191230_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='content',
        ),
    ]
