# Generated by Django 3.0.2 on 2020-01-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_postit_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='tasks',
        ),
        migrations.AddField(
            model_name='postit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
