# Generated by Django 3.0.2 on 2020-01-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200121_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='user',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
