# Generated by Django 3.0.2 on 2020-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200121_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postittask',
            name='task',
        ),
        migrations.AddField(
            model_name='postittask',
            name='task',
            field=models.ManyToManyField(null=True, to='app.Task'),
        ),
    ]
