# Generated by Django 3.0.2 on 2020-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200130_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postittask',
            name='task',
            field=models.ManyToManyField(to='app.Task'),
        ),
    ]
