# Generated by Django 3.0.2 on 2020-02-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
    ]
