# Generated by Django 3.0.2 on 2020-02-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostitTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('postit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostIt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
        ),
    ]
